customhost = "database-1.cgk3kxzd8dh0.us-east-1.rds.amazonaws.com"
customuser = "aws_user"
custompass = "Bait3273"
customdb = "employee"
custombucket = "jasdeepsinghwalia-employee"
customregion = "us-east-1"
